---
- hosts: localhost
  gather_facts: true

  roles:
    - role: validate_parms
      when: vars_validated is not defined
    - role: complete_sno_install
    - role: get_floating_ip_address
      when: fip is not defined or fip.address is not defined


  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
      when: fip.address not in groups['kvm_vsi'] | default([])
    
    - name: Generate custom hosts file for SNO cluster
      template:
        src: templates/hosts.j2
        dest: auth/{{ sno_cluster_name }}.hosts

- hosts: kvm_vsi
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "auth/{{ name_prefix }}-local-id_rsa"

  roles:
    - role: setup_haproxy

  post_tasks:
    - name: Get SNO ip address from previous play
      set_fact:
        sno_ip: "{{ hostvars['localhost']['sno_ip'] }}"

    - name: Add SNO hostnames to KVM host 
      blockinfile:
        path: /etc/hosts
        block: |
            {{ sno_ip }}	api.{{ sno_cluster_name }}.{{ sno_domain_name }}
            {{ sno_ip }}	oauth-openshift.apps.{{ sno_cluster_name }}.{{ sno_domain_name }}
            {{ sno_ip }}	console-openshift-console.apps.{{ sno_cluster_name }}.{{ sno_domain_name }}
            {{ sno_ip }}	grafana-openshift-monitoring.apps.{{ sno_cluster_name }}.{{ sno_domain_name }}
            {{ sno_ip }}	thanos-querier-openshift-monitoring.apps.{{ sno_cluster_name }}.{{ sno_domain_name }}
            {{ sno_ip }}	prometheus-k8s-openshift-monitoring.apps.{{ sno_cluster_name }}.{{ sno_domain_name }}
            {{ sno_ip }}	alertmanager-main-openshift-monitoring.apps.{{ sno_cluster_name }}.{{ sno_domain_name }}

    - name: Show access info
      vars:
         msg: |
                The OpenShift SNO cluster is ready ! 

                You can access the KVM host via SSH with:
                  ssh -i {{ playbook_dir}}/auth/{{ name_prefix}}-local-id_rsa kvmadmin@{{ hostvars['localhost']['fip.address'] }}

                Your OpenShift cluster credentials are in the file {{ playbook_dir}}/auth/{{ sno_cluster_name }}-kubeadmin.json

                To access the OpenShift console:

                  1. Add the contents of the file {{ playbook_dir}}/auth/{{ sno_cluster_name }}.hosts to your /etc/hosts file

                  2. You can then access the OpenShift console at the following  URL:
                     https://console-openshift-console.apps.{{ sno_cluster_name }}.{{ sno_domain_name }}

                To access the cluster via the oc CLI run the following command:

                  oc login api.{{ sno_cluster_name }}.{{ sno_domain_name }}:6443 and login with your credentials 

      debug:
        msg: "{{ msg.split('\n') }}"


