---
- hosts: localhost
  gather_facts: true
  
  roles:
    - role: validate_parms
      when: vars_validated is not defined
    - role: get_floating_ip_address
      when: fip is not defined or fip.address is not defined

  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
      when: fip.address not in groups['kvm_vsi'] | default([])

- hosts: kvm_vsi
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/{{ name_prefix }}-id_rsa"

  roles:
    - role: create_utility_vm

  post_tasks:

    - name: Show VM info
      vars:
         msg: |
                The VM for installing OpenShift SNO have been created !

                You can access the SNO utility VM from the KVM VSI with:
                  ssh root@192.168.122.2

      debug:
        msg: "{{ msg.split('\n') }}"
