---
- hosts: localhost
  gather_facts: true
  collections:
    - ibm.cloudcollection

  roles:
    - role: validate_parms
      when: vars_validated is not defined
    - role: get_floating_ip_address
      when: fip is not defined or fip.address is not defined
    - role: prepare_sno_install

  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
      when: fip.address not in groups['kvm_vsi'] | default([])

- hosts: kvm_vsi
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/{{ name_prefix }}-id_rsa"

  pre_tasks:
    - name: Get ISO download URL from previous play
      set_fact:
        download_url: "{{ hostvars['localhost']['download_url'] }}"

  roles:
    - role: create_sno_vm
  
  post_tasks:
    - name: Success message
      debug:
        msg: "Your SNO cluster is ready to install"

- hosts: localhost
  gather_facts: true

  roles:
    - role: start_sno_install

  post_tasks:
    - name: Success message
      debug:
        msg: "Your SNO install started successfully !"
        