---
- hosts: localhost
  gather_facts: true
  collections:
    - community.general

  roles:
    - role: validate_parms
      when: vars_validated is not defined
    - role: provision_kvm_host

  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
      when: fip.address not in groups['kvm_vsi'] | default([])

    - name: Wait for VSI to become reachable over SSH
      wait_for:
        host: "{{ fip.address }}"
        port: 22
        delay: 20
        timeout: 180
        sleep: 10
        state: started

- hosts: kvm_vsi
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/{{ name_prefix }}-id_rsa"

  pre_tasks:

    - name: Install Python on remote server for Ansible
      raw: "{{ item }}"
      loop:
        - yum update -y
        - yum install -y python3

    - name: Collect OS information
      command: cat /etc/os-release
      register: os_info


    - name: Print OS information
      debug:
        var: os_info.stdout_lines

    - name: Get Floating IP info from previous play
      set_fact:
        fip: "{{ hostvars['localhost']['fip']}}"

  roles:
    - role: format_data_disk
    - role: disable_se_linux
    - role: reboot_vsi
      when: selinux_out is defined and selinux_out.reboot_required

  post_tasks:

    - name: Show access info
      vars:

         msg: |
                Your VSI has been successfully provisioned !
                Login in via SSH using the command:
                ssh -i ~/.ssh/{{ name_prefix }}-id_rsa root@{{ fip.address }}
      debug:
        msg: "{{ msg.split('\n') }}"
