---
- name: Get VSIs IP and add to inventory if not already there
  hosts: localhost
  gather_facts: true
  collections:
    - community.general
    - ansible.posix


  roles:
      - role: validate_parms
        when: vars_validated is not defined
      - role: get_floating_ip_address
        when: fip is not defined or fip.address is not defined

  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
      when: fip.address not in groups['kvm_vsi'] | default([])


- hosts: kvm_vsi
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/{{ name_prefix }}-id_rsa"

  pre_tasks:
    - name: Get Floating IP info from previous play
      set_fact:
        fip: "{{ hostvars['localhost']['fip'] }}"

  roles:
    - name: install_gui
    - name: reboot_vsi
      when: install_gui_out is defined and install_gui_out.changed

  post_tasks:

    - name: Show access info
      vars:
         msg: |
                Your VSIs GUI enviroment has been installed successfully !
                Setup VNC or RDP to start accessing it
                You can still access your VSI by logging in via SSH:
                     ssh -i ~/.ssh/{{ name_prefix }}-id_rsa kvmadmin@{{ fip.address }}
                For root access you can prefix each command with sudo as shown below:
                      sudo dnf install -y my-favorite-utility
      debug:
        msg: "{{ msg.split('\n') }}"
