---
- hosts: localhost
  gather_facts: true
  collections:
    - community.general
    - ansible.posix

  roles:
    - role: validate_parms
      when: vars_validated is not defined
    - role: get_floating_ip_address
      when: fip is not defined or fip.address is not defined

  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
      when: fip.address not in groups['kvm_vsi'] | default([])

- hosts: kvm_vsi
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "auth/{{ name_prefix }}-local-id_rsa"

  roles:
    - setup_rdp

  post_tasks:

    - name: Get Floating IP info from previous plays
      set_fact:
        fip: "{{ hostvars['localhost']['fip'] }}"

    - name: Show access info
      vars:
         msg: |
                The GUI env with RDP access has been configured !
                You will need to set a password for the kvmadmin user because RDP
                clients will require one

                To set the kvmadmin password login in via SSH using the command:

                ssh -i {{ playbook_dir }}/auth/{{ name_prefix }}-local-id_rsa kvmadmin@{{ fip.address }}

                Then run the following command:

                   sudo passwd kvmadmin

                That's it ! You can access via RDP by pointing your RDP client to:

                   {{ fip.address }}:3389

                and entering the kvmadmin uaer password when prompted.

      debug:
        msg: "{{ msg.split('\n') }}"
