---
- hosts: localhost
  gather_facts: true
  collections:
    - ibm.cloudcollection
    - community.general
    - ansible.posix

  tasks:
    - name: Verify that IBM Cloud API KEY is defined
      assert:
        that: lookup('env','IC_API_KEY') != ""
        fail_msg: "IC_API_KEY env variable is required for this playbook "
        success_msg: "IBM Cloud API KEY is defined"

    - name: "Verify that required variables are defined"
      assert:
        that:  "{{ item }} is defined"
        fail_msg: "variable {{ item }} is required for this playbook "
        success_msg: "Required variable {{ item }} is defined"
      with_items:
        - name_prefix
        - region
        - ssh_public_key_path

    - name: Get VSIs floating IP if we don't have it yet
      block:
        - name: Get KVM VSIs floating IP
          ibm_is_floating_ip_info:
            name: "{{ name_prefix }}-fip"
            region: "{{ region }}"
          register: fip_info_output

        - name: Save floating IP as fact
          set_fact:
            cacheable: true
            fip: "{{ fip_info_output.resource }}"

        - name: Verify that floating IP's ipv4 address is defined
          assert:
            that: fip.address is defined
            fail_msg: "IP address of KVM VSI is required for this playbook "
            success_msg: "IP address of KVM VSI is {{ fip.address }} "

 
      when: fip is not defined or fip.address is not defined

  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
      when: fip.address not in groups['kvm_vsi'] | default([])

- hosts: kvm_vsi
  gather_facts: false
  become: yes

  roles:
    - setup_vnc

  post_tasks:

    - name: Get Floating IP info from previous plays
      set_fact:
        fip: "{{ hostvars['localhost']['fip'] }}"

    - name: Show access info
      vars:
         msg: |
                The GUI env with VNC access has been configured !
                You need to set your VNC password before accessing via VNC.
                Login in via SSH using the command:
                    ssh kvmadmin@{{ fip.address }}
                Set the VNC password by running the following command:
                    vncpasswd
                You will also need to set a password for the kvmadmin user because the
                GNOME desktop has a lock screen that requires that  password to unlock.
                Run the following commands in the same SSH session to set the kvmadmin user password:
                    sudo bash
                    passwd kvmadmin
                    exit
                That's it ! You can access via VNC now by pointing your VNC client to:
                   {{ fip.address }}:5901  and entering your VNC password when prompted.

      debug:
        msg: "{{ msg.split('\n') }}"
