---
- hosts: localhost
  gather_facts: true
  collections:
    - community.general

  roles:
    - role: validate_parms
      when: vars_validated is not defined

  post_tasks:
    - name: Success message
      debug:
        msg: "Parameter validation successful"
